version: '3.4'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=642f45a4-111b-4de2-8a85-4b1737deb8e9
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/WebApi.pfx
    ports:
      - 8081:80
      - 8082:443
    volumes:
      # - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./ssl_cer:/https:ro